projects:
  fyshios:
    schemaPath: amplify/backend/api/fyshios/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
